// Array com 12 profissionais simulados - Atende ao requisito de 10+
const professionals = [
  {
    id: 1,
    name: "Mariana Souza",
    role: "Designer de Produto",
    location: "São Paulo - SP",
    experience: 3,
    education: "Design, Universidade de São Paulo",
    avatar: "https://i.pravatar.cc/150?img=1",
    technicalSkills: ["UX Design", "Figma", "Prototipagem", "User Research"],
    softSkills: [
      "Comunicação",
      "Empatia",
      "Criatividade",
      "Resolução de Problemas",
    ],
    hobbies: ["Fotografia", "Café", "Ilustração"],
    area: "Design",
    technologies: ["Figma", "Adobe XD"],
  },
  {
    id: 2,
    name: "Lucas Pereira",
    role: "Desenvolvedor Front-End",
    location: "Campinas - SP",
    experience: 2,
    education: "Análise e Desenvolvimento de Sistemas, FATEC",
    avatar: "https://i.pravatar.cc/150?img=2",
    technicalSkills: ["HTML", "CSS", "JavaScript", "React"],
    softSkills: ["Responsabilidade", "Trabalho em equipe", "Adaptabilidade"],
    hobbies: ["Corrida", "Jogos", "Streaming"],
    area: "Desenvolvimento",
    technologies: ["React", "JavaScript", "HTML"],
  },
  {
    id: 3,
    name: "Ana Ribeiro",
    role: "Analista de Dados",
    location: "Rio de Janeiro - RJ",
    experience: 1,
    education: "Estatística, Universidade Federal do Rio de Janeiro",
    avatar: "https://i.pravatar.cc/150?img=3",
    technicalSkills: ["SQL", "Power BI", "Python", "Análise Estatística"],
    softSkills: ["Pensamento crítico", "Atenção ao detalhe", "Comunicação"],
    hobbies: ["Leitura", "Podcasts", "Viagens"],
    area: "Dados",
    technologies: ["Python", "SQL", "Power BI"],
  },
  {
    id: 4,
    name: "Bruno Lima",
    role: "Engenheiro de Cloud",
    location: "Belo Horizonte - MG",
    experience: 4,
    education: "Engenharia de Computação, UFMG",
    avatar: "https://i.pravatar.cc/150?img=4",
    technicalSkills: ["Azure", "Docker", "Kubernetes", "Terraform"],
    softSkills: ["Organização", "Liderança", "Pensamento estratégico"],
    hobbies: ["Mountain bike", "Camping", "Tecnologia"],
    area: "Cloud",
    technologies: ["Azure", "Docker"],
  },
  {
    id: 5,
    name: "Carolina Alves",
    role: "Analista de Cibersegurança",
    location: "Porto Alegre - RS",
    experience: 2,
    education: "Segurança da Informação, PUCRS",
    avatar: "https://i.pravatar.cc/150?img=5",
    technicalSkills: ["SIEM", "Pentest", "Forense Digital", "Python"],
    softSkills: ["Detalhismo", "Persistência", "Comunicação técnica"],
    hobbies: ["Quebra-cabeças", "Hacking ético", "CTF"],
    area: "Segurança",
    technologies: ["Python", "Linux"],
  },
  {
    id: 6,
    name: "Diego Costa",
    role: "Desenvolvedor Back-End",
    location: "Curitiba - PR",
    experience: 3,
    education: "Ciência da Computação, UFPR",
    avatar: "https://i.pravatar.cc/150?img=6",
    technicalSkills: ["Node.js", "SQL", "PostgreSQL", "API REST"],
    softSkills: ["Resiliência", "Colaboração", "Documentação"],
    hobbies: ["Culinária", "Viagens", "Música"],
    area: "Desenvolvimento",
    technologies: ["Node.js", "SQL"],
  },
  {
    id: 7,
    name: "Elisa Martins",
    role: "Especialista em RH",
    location: "Fortaleza - CE",
    experience: 3,
    education: "Administração, UFC",
    avatar: "https://i.pravatar.cc/150?img=7",
    technicalSkills: ["Recrutamento", "People Ops", "HRIS", "Análise de Dados"],
    softSkills: ["Empatia", "Escuta ativa", "Negociação"],
    hobbies: ["Yoga", "Meditação", "Desenvolvimento pessoal"],
    area: "Recursos Humanos",
    technologies: ["SAP", "HR Systems"],
  },
  {
    id: 8,
    name: "Felipe Rocha",
    role: "Desenvolvedor Mobile",
    location: "Manaus - AM",
    experience: 2,
    education: "Engenharia de Software, UEA",
    avatar: "https://i.pravatar.cc/150?img=8",
    technicalSkills: ["Flutter", "Dart", "UI Mobile", "Firebase"],
    softSkills: ["Criatividade", "Inovação", "Soluções rápidas"],
    hobbies: ["Música", "Produção de áudio", "Arte digital"],
    area: "Desenvolvimento",
    technologies: ["Flutter", "Dart"],
  },
  {
    id: 9,
    name: "Gabriela Nunes",
    role: "Engenheira de QA",
    location: "Recife - PE",
    experience: 1,
    education: "Engenharia de Software, UFPE",
    avatar: "https://i.pravatar.cc/150?img=9",
    technicalSkills: [
      "Selenium",
      "Testes Automatizados",
      "API Testing",
      "Python",
    ],
    softSkills: ["Curiosidade", "Raciocínio lógico", "Qualidade"],
    hobbies: ["Escalada", "Leitura técnica", "Gaming"],
    area: "Qualidade",
    technologies: ["Selenium", "Python"],
  },
  {
    id: 10,
    name: "Hugo Fernandes",
    role: "Growth Marketer",
    location: "Salvador - BA",
    experience: 3,
    education: "Marketing Digital, UNIFACS",
    avatar: "https://i.pravatar.cc/150?img=10",
    technicalSkills: ["SEO", "Google Analytics", "SEM", "Data Analysis"],
    softSkills: ["Comunicação", "Estratégia", "Criatividade"],
    hobbies: ["Surf", "Fotografia", "Empreendedorismo"],
    area: "Marketing",
    technologies: ["Google Analytics", "SEO Tools"],
  },
  {
    id: 11,
    name: "Juliana Costa",
    role: "Arquiteta de Soluções",
    location: "São Paulo - SP",
    experience: 5,
    education: "Engenharia de Computação, USP",
    avatar: "https://i.pravatar.cc/150?img=11",
    technicalSkills: ["Arquitetura Corporativa", "Microserviços", "Cloud"],
    softSkills: ["Visão estratégica", "Mentoria", "Comunicação"],
    hobbies: ["Conferências", "Arquitetura", "Mentoring"],
    area: "Arquitetura",
    technologies: ["Azure", "AWS"],
  },
  {
    id: 12,
    name: "Rafael Santos",
    role: "DevOps Engineer",
    location: "Brasília - DF",
    experience: 4,
    education: "Administração de Sistemas, UnB",
    avatar: "https://i.pravatar.cc/150?img=12",
    technicalSkills: ["CI/CD", "Kubernetes", "Jenkins", "Ansible"],
    softSkills: ["Automação", "Planejamento", "Colaboração"],
    hobbies: ["Open Source", "Configuração de infra", "Comunidades tech"],
    area: "DevOps",
    technologies: ["Kubernetes", "Jenkins"],
  },
];

// Quiz com perguntas por categoria
const quizQuestions = [
  // Por Área
  {
    id: 1,
    category: "area",
    question: "Qual é a principal responsabilidade de um Data Analyst?",
    options: [
      "Coletar, processar e interpretar dados",
      "Desenhar interfaces",
      "Gerenciar infraestrutura",
    ],
    correct: 0,
    area: "Dados",
  },
  {
    id: 2,
    category: "area",
    question: "O que diferencia um Frontend Developer de um Backend Developer?",
    options: [
      "Nada, é a mesma coisa",
      "Frontend trabalha com interface, Backend com lógica de servidor",
      "Frontend usa mais tecnologia",
    ],
    correct: 1,
    area: "Desenvolvimento",
  },
  {
    id: 3,
    category: "area",
    question: "Qual é o foco principal de um DevOps Engineer?",
    options: [
      "Design de produtos",
      "Automação e integração de processos de desenvolvimento",
      "Recrutamento",
    ],
    correct: 1,
    area: "DevOps",
  },
  {
    id: 4,
    category: "area",
    question: "Um Especialista em Cibersegurança principalmente trabalha com:",
    options: [
      "Criação de logos",
      "Proteção contra ameaças digitais",
      "Vendas de produtos",
    ],
    correct: 1,
    area: "Segurança",
  },

  // Por Tecnologia
  {
    id: 5,
    category: "technology",
    question: "React é principalmente usado para:",
    options: [
      "Processamento de dados",
      "Construção de interfaces web interativas",
      "Administração de sistemas",
    ],
    correct: 1,
    technology: "React",
  },
  {
    id: 6,
    category: "technology",
    question: "Qual é a principal vantagem do Docker?",
    options: [
      "Desempenho rápido",
      "Consistência entre ambientes",
      "Segurança absoluta",
    ],
    correct: 1,
    technology: "Docker",
  },
  {
    id: 7,
    category: "technology",
    question: "Python é conhecido por ser:",
    options: [
      "Muito rápido",
      "Difícil de aprender",
      "Versátil e fácil de aprender",
    ],
    correct: 2,
    technology: "Python",
  },
  {
    id: 8,
    category: "technology",
    question: "Kubernetes é usado principalmente para:",
    options: [
      "Edição de fotos",
      "Orquestração de containers",
      "Marketing digital",
    ],
    correct: 1,
    technology: "Kubernetes",
  },

  // Por Cidade
  {
    id: 9,
    category: "city",
    question: "São Paulo é conhecida como o maior polo de:",
    options: ["Turismo", "Tecnologia e negócios do Brasil", "Agricultura"],
    correct: 1,
    city: "São Paulo",
  },
  {
    id: 10,
    category: "city",
    question: "Qual região brasileira é considerada um hub tecnológico?",
    options: [
      "Vale do Silício Brasileiro (Campinas/SP)",
      "Interior de Goiás",
      "Litoral de Pernambuco",
    ],
    correct: 0,
    city: "Campinas",
  },
  {
    id: 11,
    category: "city",
    question: "Brasília é importante para o mercado de tecnologia por:",
    options: [
      "Praias bonitas",
      "Presença de órgãos governamentais e demanda por tech",
      "Culinária",
    ],
    correct: 1,
    city: "Brasília",
  },
  {
    id: 12,
    category: "city",
    question:
      "Rio de Janeiro tem crescimento significativo em qual setor tech?",
    options: ["Manufatura", "Análise de dados e startups", "Apenas turismo"],
    correct: 1,
    city: "Rio de Janeiro",
  },
];
